name: Deploy

on:
  push:
    branches: ["dev"]

jobs:
  build-deploy-backend:
    runs-on: self-hosted

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Use Node.js 18x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Run install
        working-directory: ./backend
        run: |
          npm install

      - name: Run build
        working-directory: ./backend
        run: |
          npm run build

      - name: Run build
        working-directory: ./backend
        run: |
            touch .env
            echo "${{ secrets.PROD_ENV_FILE }}" > .env
            pm2 restart dist/bundle.js --name "wolfjobs_backend"


