name: Deploy

on:
  push:
    branches: ["dev"]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Use Node.js 18x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Run install
        working-directory: ./backend
        run: |
          npm install

      - name: Run build
        working-directory: ./backend
        run: |
          npm run build

      - name: Run build
        working-directory: ./backend
        run: |
            touch .env
            echo "${{ secrets.PROD_ENV_FILE }}" > .env
      - name: Delete existing pm2 service
        working-directory: ./backend
        continue-on-error: true
        run: |
            pm2 delete wolfjobs_backend
    
      - name: Start pm2 service
        working-directory: ./backend
        continue-on-error: true
        run: |
            pm2 start ./dist/bundle.js --name wolfjobs_backend
    
      - name: Install dependency for frontend
        working-directory: ./frontend
        run: |
          npm install
    
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm run build

      - name: Nginx Loading
        run: |
          sudo rm -rf /usr/share/nginx/html/*
          sudo cp -r ./frontend/dist/* /usr/share/nginx/html/
          sudo systemctl restart nginx

